[versions]
jackson-core = "2.20.0"
jackson-annotations = "2.20"
jakarta-annotations = "3.0.0"
junit = "6.0.2"
openapi-generator = "7.18.0"

[libraries]
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson-annotations" }
jackson-databind = { module = " com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-core" }
jakarta-annotations = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotations" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

[plugins]
develocityApiConventions = { id = "conventions.develocity-api" }
javaLibrary = { id = "java-library" }
javaTestFixtures = { id = "java-test-fixtures" }
openapiGenerator = { id = "org.openapi.generator", version.ref = "openapi-generator" }
releaseConventions = { id = "conventions.release" }
