[versions]
jackson-core = "2.17.1"
jakarta-annotation = "3.0.0"
junit = "5.10.3"
openapi-generator = "7.7.0"

[libraries]
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson-core" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-core" }
jakarta-annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

[plugins]
develocity-api-models = { id = "conventions.develocity-api-models" }
java-library = { id = "java-library" }
java-test-fixtures = { id = "java-test-fixtures" }
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }
